name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Go application
      run: go build -o app

    - name: Build Docker image
      run: docker build -t panda8z/mainpage .

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Set up Docker Compose
      uses: docker/compose-cli-action@v1
      with:
        version: '1.29.2'

    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push your-app-name

    - name: Deploy to server
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server-ip 'bash -s' < deploy.sh
